### ISSUE TITLE
What is this project used for?

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/css#28]
Why is there a css project?  Could the functionality provided be added to the readme.md.

**Comment by matthewp** [comment]
This is the normal Steal CSS plugin with a few DoneJS specific features like live-reload and server-side rendering included.  At the time I wanted to avoid adding bulk to the normal CSS plugin for basic usage, but now I think it would be better to move the non-essential parts to a second module and simply exclude it from the build.

**Comment by pYr0x** [comment]
i think we should use the steal-css plugin as basic and add some features to `done-css`. but the basic module should be `steal-css` because we added some important stuff there.

**Comment by matthewp** [comment]
I would probably just merge them.

**Comment by pYr0x** [comment]
@matthewp yep, sound good. we use steal-css for all donejs projects then?

**Comment by matthewp** [comment]
Yeah, sounds good to me, but this one has SSR and live-reload tests/code that needs to be moved there.

**Comment by matthewp** [comment]
We've figured this all out.
