### ISSUE TITLE
Meta deps do not work

### ISSUE THREAD

**Issue by akagomez** [donejs/css#41]
```
"meta": {
  "egowall/pages/hub/hub.less!$less": {
    "deps": [
      "egowall/less/bootstrap/bootstrap.less!$less"
    ]
  }
}
```

@matthewp mentioned it may be due to this line: https://github.com/donejs/css/blob/master/css.js#L93

**Comment by akagomez** [comment]
This worked: 

```
load.metadata.deps = (loader.meta[load.name] && loader.meta[load.name].deps) || [];
```

**Comment by akagomez** [comment]
While this did load the file, it did so AFTER the target file. Might be a less-engine thing.

**Comment by matthewp** [comment]
when you say load you mean the style tag for the dependency was added second?

**Comment by akagomez** [comment]
That's right.

**Comment by matthewp** [comment]
strange, but should be easily testable I think.
